# Generated by Django 6.1 on 2026-08-27 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProduitMado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('path', models.CharField(default='#', max_length=500)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_unite_in_pack', models.PositiveIntegerField(blank=True, null=True)),
                ('is_unite', models.BooleanField(default=False)),
                ('poid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'produit_mado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('produit_like', models.ForeignKey(blank=True, db_column='produit_like', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_likes', to='sainto_mg.produitmado')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['-date'],
            },
        ),
    ]
