# Generated by Django 6.1 on 2026-08-27 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='produitmado',
            options={},
        ),
        migrations.RemoveField(
            model_name='client',
            name='produit_like',
        ),
        migrations.CreateModel(
            name='ProduitLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sainto_mg.client')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sainto_mg.produitmado')),
            ],
            options={
                'db_table': 'produit_like',
                'constraints': [models.UniqueConstraint(fields=('client', 'produit'), name='unique_client_produit_like')],
            },
        ),
    ]
