# Generated by Django 6.1 on 2026-08-27 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0002_alter_client_options_alter_produitmado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
