# Generated by Django 6.1 on 2026-08-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0003_client_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produitmado',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
