# Generated by Django 6.1 on 2026-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0004_alter_produitmado_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.ImageField(upload_to='pub/')),
            ],
            options={
                'db_table': 'pub',
            },
        ),
    ]
