# Generated by Django 6.1 on 2026-08-27 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0005_pub'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='produitlike',
            name='unique_client_produit_like',
        ),
    ]
