# Generated by Django 6.1 on 2026-08-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sainto_mg', '0006_remove_produitlike_unique_client_produit_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='rating',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
